app_admin:
    resource: "@AppBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

app_home:
    path: /
    defaults: { _controller: AppBundle:App:home }

app_science:
        resource: "@AppBundle/Resources/config/routing/science.yml"
        prefix:   /science

app_publication:
        resource: "@AppBundle/Resources/config/routing/publication.yml"
        prefix:   /publication