AppBundle\Entity\Publication:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PublicationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '128'
        author:
            type: string
            length: '64'
        description:
            type: string
            length: '255'
        content:
            type: text
        publishedAt:
            type: datetime
        validated:
            type: boolean
    ManyToOne:
           science:
               targetEntity: AppBundle\Entity\Science
               joinColumn:
                   name: science
                   referencedColumnName: id
    lifecycleCallbacks: {  }

